#!/usr/bin/env python3
"""
apply-theme.py — Write real theme colors and fonts into a .pptx generated by pptxgenjs.

pptxgenjs can set the theme *fonts* but cannot write theme *colors*: every deck it
produces ships with Office's stock palette in ppt/theme/theme1.xml. This script
replaces that palette (and the font pair) with the ones you designed, so that:

  - scheme colors used in the generator (pres.SchemeColor.accent1, text1, ...)
    resolve to your palette instead of Office blue/orange,
  - the user can recolor the whole deck later from PowerPoint's Design > Variants,
  - charts, tables, and placeholders inherit the right fonts.

Usage:
    python scripts/apply-theme.py deck.pptx theme.json
    python scripts/apply-theme.py deck.pptx --json '{"name": "...", ...}'

theme.json shape (all keys optional except colors you want to set):
{
  "name": "Signal",
  "headFontFace": "Source Serif 4",
  "bodyFontFace": "DM Sans",
  "eaFontFace": "Noto Sans KR",          # optional East-Asian font for both roles
  "colors": {
    "dk1": "1A2030", "lt1": "F0ECE3", "dk2": "1C2644", "lt2": "E6E0D4",
    "accent1": "C8A870", "accent2": "232F55", "accent3": "8A96A8",
    "accent4": "4E5A6E", "accent5": "CAC4B4", "accent6": "2E3D5C",
    "hlink": "C8A870", "folHlink": "8A96A8"
  }
}

Colors are 6-digit hex with or without a leading '#'. Only stdlib is used.
"""

import argparse
import json
import os
import re
import shutil
import sys
import tempfile
import zipfile

COLOR_KEYS = [
    "dk1", "lt1", "dk2", "lt2",
    "accent1", "accent2", "accent3", "accent4", "accent5", "accent6",
    "hlink", "folHlink",
]


def norm_hex(value, key):
    v = str(value).strip().lstrip("#").upper()
    if not re.fullmatch(r"[0-9A-F]{6}", v):
        raise SystemExit(f"Theme color '{key}' must be 6-digit hex, got '{value}'")
    return v


def xml_escape(text):
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def patch_theme_xml(xml, theme):
    """Return theme XML with colors / fonts / name replaced."""
    colors = theme.get("colors") or {}

    for key in COLOR_KEYS:
        if key not in colors:
            continue
        hexval = norm_hex(colors[key], key)
        pattern = re.compile(rf"<a:{key}>.*?</a:{key}>", re.S)
        if not pattern.search(xml):
            raise SystemExit(f"theme XML has no <a:{key}> element; is this a valid .pptx?")
        xml = pattern.sub(f'<a:{key}><a:srgbClr val="{hexval}"/></a:{key}>', xml, count=1)

    name = theme.get("name")
    if name:
        safe = xml_escape(name)
        xml = re.sub(r'<a:clrScheme name="[^"]*"', f'<a:clrScheme name="{safe}"', xml, count=1)
        xml = re.sub(r'<a:fontScheme name="[^"]*"', f'<a:fontScheme name="{safe}"', xml, count=1)
        xml = re.sub(r'<a:theme([^>]*) name="[^"]*"', rf'<a:theme\1 name="{safe}"', xml, count=1)

    def set_font(xml, block, role_tag, face):
        safe = xml_escape(face)
        pattern = re.compile(rf"(<a:{block}>.*?<a:{role_tag} typeface=\")[^\"]*(\")", re.S)
        if not pattern.search(xml):
            raise SystemExit(f"theme XML has no <a:{block}><a:{role_tag}> element")
        return pattern.sub(rf"\g<1>{safe}\g<2>", xml, count=1)

    if theme.get("headFontFace"):
        xml = set_font(xml, "majorFont", "latin", theme["headFontFace"])
    if theme.get("bodyFontFace"):
        xml = set_font(xml, "minorFont", "latin", theme["bodyFontFace"])
    if theme.get("eaFontFace"):
        xml = set_font(xml, "majorFont", "ea", theme["eaFontFace"])
        xml = set_font(xml, "minorFont", "ea", theme["eaFontFace"])
    return xml


def apply_theme(pptx_path, theme):
    if not zipfile.is_zipfile(pptx_path):
        raise SystemExit(f"Not a .pptx (zip) file: {pptx_path}")

    tmp_fd, tmp_path = tempfile.mkstemp(suffix=".pptx", dir=os.path.dirname(os.path.abspath(pptx_path)))
    os.close(tmp_fd)
    patched = 0
    try:
        with zipfile.ZipFile(pptx_path, "r") as zin, zipfile.ZipFile(tmp_path, "w", zipfile.ZIP_DEFLATED) as zout:
            for item in zin.infolist():
                data = zin.read(item.filename)
                if re.fullmatch(r"ppt/theme/theme\d+\.xml", item.filename):
                    data = patch_theme_xml(data.decode("utf-8"), theme).encode("utf-8")
                    patched += 1
                zout.writestr(item, data)
        shutil.move(tmp_path, pptx_path)
    finally:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)
    return patched


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("pptx", help="deck to patch in place")
    ap.add_argument("theme", nargs="?", help="theme.json path")
    ap.add_argument("--json", help="inline theme JSON instead of a file")
    args = ap.parse_args()

    if args.json:
        theme = json.loads(args.json)
    elif args.theme:
        with open(args.theme, "r", encoding="utf-8") as f:
            theme = json.load(f)
    else:
        ap.error("give a theme.json path or --json")

    n = apply_theme(args.pptx, theme)
    print(f"Applied theme to {n} theme part(s) in {args.pptx}")
    set_colors = [k for k in COLOR_KEYS if k in (theme.get("colors") or {})]
    if set_colors:
        print("  colors: " + ", ".join(set_colors))
    for k in ("headFontFace", "bodyFontFace", "eaFontFace"):
        if theme.get(k):
            print(f"  {k}: {theme[k]}")


if __name__ == "__main__":
    main()
